version: '3'

services:
  # redis
  redis:
    image: "redis:latest"
  # app
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"
      MAX_REQUEST_IP_PER_SECOND: 10
      MAX_REQUEST_TOKEN_PER_SECOND: 20
      TIME_LOCK_IN_SECOND: 10    
    depends_on:
      - redis
